In [4]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b =a.tolist()
print(b)

[[1, 2, 3], [4, 5, 6]]


In [5]:
import numpy as np
a = np.arange(8).reshape((2,2,2))
np.trace(a)

array([6, 8])

In [6]:
import numpy as np
a = np.array([[3, 10, 20,30,1]])
print(np.ma.masked_less(a,2))


[[3 10 20 30 --]]


In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [8]:
import numpy as np
a=np.array([4,5,6])
b=np.mean(a)
z=a-b
print(z)


[-1.  0.  1.]
